# Generated by Django 4.2.6 on 2023-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_artikel_bestellung_bestellteartikel_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='bestelldatum',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bestelldatum'),
        ),
    ]
